
name: Refresh Dependencies

on:
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Regenerate requirements.txt
      run: |
        pip-compile --output-file=requirements.txt requirements.in
        pip-sync requirements.txt
